@extends('layout.app')
@section('content')
    @include('components.MenuBar')
    @include('components.Banner')
    @include('components.BanmerSort')
    @include('components.ExclusiveProducts')
    @include('components.BannerSingle')
    @include('components.FeaturedProducts')
    @include('components.OurClient')
    @include('components.Subscribe')
    {{-- @include('components.HeroSlider')
    @include('components.TopCategories')
    @include('components.TopBrands') --}}
    @include('components.Footer')
